package vidavo.pojos;
// Generated 18.3.2010 19:46: by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Appointments generated by hbm2java
 */
public class Appointments  implements java.io.Serializable {


     private int appointmentId;
     private Patients patients;
     private String category;
     private Date date;
     private String title;
     private Date time;
     private int duration;
     private String comments;

    public Appointments() {
    }

	
    public Appointments(int appointmentId, Patients patients, Date date, Date time, int duration) {
        this.appointmentId = appointmentId;
        this.patients = patients;
        this.date = date;
        this.time = time;
        this.duration = duration;
    }
    public Appointments(Patients patients, String category, Date date, String title, Date time, int duration, String comments) {
       this.appointmentId = appointmentId;
       this.patients = patients;
       this.category = category;
       this.date = date;
       this.title = title;
       this.time = time;
       this.duration = duration;
       this.comments = comments;
    }
   
    public int getAppointmentId() {
        return this.appointmentId;
    }
    
    public void setAppointmentId(int appointmentId) {
        this.appointmentId = appointmentId;
    }
    public Patients getPatients() {
        return this.patients;
    }
    
    public void setPatients(Patients patients) {
        this.patients = patients;
    }
    public String getCategory() {
        return this.category;
    }
    
    public void setCategory(String category) {
        this.category = category;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public Date getTime() {
        return this.time;
    }
    
    public void setTime(Date time) {
        this.time = time;
    }
    public int getDuration() {
        return this.duration;
    }
    
    public void setDuration(int duration) {
        this.duration = duration;
    }
    public String getComments() {
        return this.comments;
    }
    
    public void setComments(String comments) {
        this.comments = comments;
    }




}


