package vidavo.pojos;
// Generated 9.3.2010 22:42: by Hibernate Tools 3.2.1.GA



/**
 * ChronicDiseases generated by hbm2java
 */
public class ChronicDiseases  implements java.io.Serializable {


     private int chId;
     private Patients patients;
     private String chroniaVroxitida;
     private String vactiriakesPneumonies;
     private String pathiseisPneumonwn;
     private String aneurismaPneumonikisArtirias;
     private String diataraxesArtiriwn;
     private String allergikoAsthma;
     private String anapneustikiAneparkeia;
     private String anapneustiras;
     private String kardiopatheia;
     private String aneurismaKardias;
     private String kardiakiArithmia;
     private String vimatodotis;
     private String emfragma;
     private String egefaliko;
     private String thromvosiAgeiwn;
     private String stenosiAortikisValvidas;
     private String aneparkeiaAortikisValvidas;
     private String ageiakesPathiseis;
     private String ypotasi;
     private String ypertasi;
     private String allesMorfesYpotasis;
     private String diavitis;
     private String nososYpatos;
     private String ipatikiAneparkeia;
     private String nefrikiAneparkeia;
     private String mixanimaAimokatharsis;
     private String elkos;
     private String diataraxesEderou;
     private String diataraxesNeurikouSistimatos;
     private String erpitikoEkzema;
     private String ipatitida;
     private String leuxaimia;
     private String eleipsiSidirou;
     private String poliomuelitida;
     private String thiroeidismos;
     private String morfiThiroeidi;
     private String allesChroniesAstheneies;

    public ChronicDiseases() {
    }

	
    public ChronicDiseases(int chId, Patients patients) {
        this.chId = chId;
        this.patients = patients;
    }
    public ChronicDiseases(String chroniaVroxitida, String vactiriakesPneumonies, String pathiseisPneumonwn, String aneurismaPneumonikisArtirias, String diataraxesArtiriwn, String allergikoAsthma, String anapneustikiAneparkeia, String anapneustiras, String kardiopatheia, String aneurismaKardias, String kardiakiArithmia, String vimatodotis, String emfragma, String egefaliko, String thromvosiAgeiwn, String stenosiAortikisValvidas, String aneparkeiaAortikisValvidas, String ageiakesPathiseis, String ypotasi, String ypertasi, String allesMorfesYpotasis, String diavitis, String nososYpatos, String ipatikiAneparkeia, String nefrikiAneparkeia, String mixanimaAimokatharsis, String elkos, String diataraxesEderou, String diataraxesNeurikouSistimatos, String erpitikoEkzema, String ipatitida, String leuxaimia, String eleipsiSidirou, String poliomuelitida, String thiroeidismos, String morfiThiroeidi, String allesChroniesAstheneies) {
       this.chId = chId;
       this.patients = patients;
       this.chroniaVroxitida = chroniaVroxitida;
       this.vactiriakesPneumonies = vactiriakesPneumonies;
       this.pathiseisPneumonwn = pathiseisPneumonwn;
       this.aneurismaPneumonikisArtirias = aneurismaPneumonikisArtirias;
       this.diataraxesArtiriwn = diataraxesArtiriwn;
       this.allergikoAsthma = allergikoAsthma;
       this.anapneustikiAneparkeia = anapneustikiAneparkeia;
       this.anapneustiras = anapneustiras;
       this.kardiopatheia = kardiopatheia;
       this.aneurismaKardias = aneurismaKardias;
       this.kardiakiArithmia = kardiakiArithmia;
       this.vimatodotis = vimatodotis;
       this.emfragma = emfragma;
       this.egefaliko = egefaliko;
       this.thromvosiAgeiwn = thromvosiAgeiwn;
       this.stenosiAortikisValvidas = stenosiAortikisValvidas;
       this.aneparkeiaAortikisValvidas = aneparkeiaAortikisValvidas;
       this.ageiakesPathiseis = ageiakesPathiseis;
       this.ypotasi = ypotasi;
       this.ypertasi = ypertasi;
       this.allesMorfesYpotasis = allesMorfesYpotasis;
       this.diavitis = diavitis;
       this.nososYpatos = nososYpatos;
       this.ipatikiAneparkeia = ipatikiAneparkeia;
       this.nefrikiAneparkeia = nefrikiAneparkeia;
       this.mixanimaAimokatharsis = mixanimaAimokatharsis;
       this.elkos = elkos;
       this.diataraxesEderou = diataraxesEderou;
       this.diataraxesNeurikouSistimatos = diataraxesNeurikouSistimatos;
       this.erpitikoEkzema = erpitikoEkzema;
       this.ipatitida = ipatitida;
       this.leuxaimia = leuxaimia;
       this.eleipsiSidirou = eleipsiSidirou;
       this.poliomuelitida = poliomuelitida;
       this.thiroeidismos = thiroeidismos;
       this.morfiThiroeidi = morfiThiroeidi;
       this.allesChroniesAstheneies = allesChroniesAstheneies;
    }
   
    public int getChId() {
        return this.chId;
    }
    
    public void setChId(int chId) {
        this.chId = chId;
    }
    public Patients getPatients() {
        return this.patients;
    }
    
    public void setPatients(Patients patients) {
        this.patients = patients;
    }
    public String getChroniaVroxitida() {
        return this.chroniaVroxitida;
    }
    
    public void setChroniaVroxitida(String chroniaVroxitida) {
        this.chroniaVroxitida = chroniaVroxitida;
    }
    public String getVactiriakesPneumonies() {
        return this.vactiriakesPneumonies;
    }
    
    public void setVactiriakesPneumonies(String vactiriakesPneumonies) {
        this.vactiriakesPneumonies = vactiriakesPneumonies;
    }
    public String getPathiseisPneumonwn() {
        return this.pathiseisPneumonwn;
    }
    
    public void setPathiseisPneumonwn(String pathiseisPneumonwn) {
        this.pathiseisPneumonwn = pathiseisPneumonwn;
    }
    public String getAneurismaPneumonikisArtirias() {
        return this.aneurismaPneumonikisArtirias;
    }
    
    public void setAneurismaPneumonikisArtirias(String aneurismaPneumonikisArtirias) {
        this.aneurismaPneumonikisArtirias = aneurismaPneumonikisArtirias;
    }
    public String getDiataraxesArtiriwn() {
        return this.diataraxesArtiriwn;
    }
    
    public void setDiataraxesArtiriwn(String diataraxesArtiriwn) {
        this.diataraxesArtiriwn = diataraxesArtiriwn;
    }
    public String getAllergikoAsthma() {
        return this.allergikoAsthma;
    }
    
    public void setAllergikoAsthma(String allergikoAsthma) {
        this.allergikoAsthma = allergikoAsthma;
    }
    public String getAnapneustikiAneparkeia() {
        return this.anapneustikiAneparkeia;
    }
    
    public void setAnapneustikiAneparkeia(String anapneustikiAneparkeia) {
        this.anapneustikiAneparkeia = anapneustikiAneparkeia;
    }
    public String getAnapneustiras() {
        return this.anapneustiras;
    }
    
    public void setAnapneustiras(String anapneustiras) {
        this.anapneustiras = anapneustiras;
    }
    public String getKardiopatheia() {
        return this.kardiopatheia;
    }
    
    public void setKardiopatheia(String kardiopatheia) {
        this.kardiopatheia = kardiopatheia;
    }
    public String getAneurismaKardias() {
        return this.aneurismaKardias;
    }
    
    public void setAneurismaKardias(String aneurismaKardias) {
        this.aneurismaKardias = aneurismaKardias;
    }
    public String getKardiakiArithmia() {
        return this.kardiakiArithmia;
    }
    
    public void setKardiakiArithmia(String kardiakiArithmia) {
        this.kardiakiArithmia = kardiakiArithmia;
    }
    public String getVimatodotis() {
        return this.vimatodotis;
    }
    
    public void setVimatodotis(String vimatodotis) {
        this.vimatodotis = vimatodotis;
    }
    public String getEmfragma() {
        return this.emfragma;
    }
    
    public void setEmfragma(String emfragma) {
        this.emfragma = emfragma;
    }
    public String getEgefaliko() {
        return this.egefaliko;
    }
    
    public void setEgefaliko(String egefaliko) {
        this.egefaliko = egefaliko;
    }
    public String getThromvosiAgeiwn() {
        return this.thromvosiAgeiwn;
    }
    
    public void setThromvosiAgeiwn(String thromvosiAgeiwn) {
        this.thromvosiAgeiwn = thromvosiAgeiwn;
    }
    public String getStenosiAortikisValvidas() {
        return this.stenosiAortikisValvidas;
    }
    
    public void setStenosiAortikisValvidas(String stenosiAortikisValvidas) {
        this.stenosiAortikisValvidas = stenosiAortikisValvidas;
    }
    public String getAneparkeiaAortikisValvidas() {
        return this.aneparkeiaAortikisValvidas;
    }
    
    public void setAneparkeiaAortikisValvidas(String aneparkeiaAortikisValvidas) {
        this.aneparkeiaAortikisValvidas = aneparkeiaAortikisValvidas;
    }
    public String getAgeiakesPathiseis() {
        return this.ageiakesPathiseis;
    }
    
    public void setAgeiakesPathiseis(String ageiakesPathiseis) {
        this.ageiakesPathiseis = ageiakesPathiseis;
    }
    public String getYpotasi() {
        return this.ypotasi;
    }
    
    public void setYpotasi(String ypotasi) {
        this.ypotasi = ypotasi;
    }
    public String getYpertasi() {
        return this.ypertasi;
    }
    
    public void setYpertasi(String ypertasi) {
        this.ypertasi = ypertasi;
    }
    public String getAllesMorfesYpotasis() {
        return this.allesMorfesYpotasis;
    }
    
    public void setAllesMorfesYpotasis(String allesMorfesYpotasis) {
        this.allesMorfesYpotasis = allesMorfesYpotasis;
    }
    public String getDiavitis() {
        return this.diavitis;
    }
    
    public void setDiavitis(String diavitis) {
        this.diavitis = diavitis;
    }
    public String getNososYpatos() {
        return this.nososYpatos;
    }
    
    public void setNososYpatos(String nososYpatos) {
        this.nososYpatos = nososYpatos;
    }
    public String getIpatikiAneparkeia() {
        return this.ipatikiAneparkeia;
    }
    
    public void setIpatikiAneparkeia(String ipatikiAneparkeia) {
        this.ipatikiAneparkeia = ipatikiAneparkeia;
    }
    public String getNefrikiAneparkeia() {
        return this.nefrikiAneparkeia;
    }
    
    public void setNefrikiAneparkeia(String nefrikiAneparkeia) {
        this.nefrikiAneparkeia = nefrikiAneparkeia;
    }
    public String getMixanimaAimokatharsis() {
        return this.mixanimaAimokatharsis;
    }
    
    public void setMixanimaAimokatharsis(String mixanimaAimokatharsis) {
        this.mixanimaAimokatharsis = mixanimaAimokatharsis;
    }
    public String getElkos() {
        return this.elkos;
    }
    
    public void setElkos(String elkos) {
        this.elkos = elkos;
    }
    public String getDiataraxesEderou() {
        return this.diataraxesEderou;
    }
    
    public void setDiataraxesEderou(String diataraxesEderou) {
        this.diataraxesEderou = diataraxesEderou;
    }
    public String getDiataraxesNeurikouSistimatos() {
        return this.diataraxesNeurikouSistimatos;
    }
    
    public void setDiataraxesNeurikouSistimatos(String diataraxesNeurikouSistimatos) {
        this.diataraxesNeurikouSistimatos = diataraxesNeurikouSistimatos;
    }
    public String getErpitikoEkzema() {
        return this.erpitikoEkzema;
    }
    
    public void setErpitikoEkzema(String erpitikoEkzema) {
        this.erpitikoEkzema = erpitikoEkzema;
    }
    public String getIpatitida() {
        return this.ipatitida;
    }
    
    public void setIpatitida(String ipatitida) {
        this.ipatitida = ipatitida;
    }
    public String getLeuxaimia() {
        return this.leuxaimia;
    }
    
    public void setLeuxaimia(String leuxaimia) {
        this.leuxaimia = leuxaimia;
    }
    public String getEleipsiSidirou() {
        return this.eleipsiSidirou;
    }
    
    public void setEleipsiSidirou(String eleipsiSidirou) {
        this.eleipsiSidirou = eleipsiSidirou;
    }
    public String getPoliomuelitida() {
        return this.poliomuelitida;
    }
    
    public void setPoliomuelitida(String poliomuelitida) {
        this.poliomuelitida = poliomuelitida;
    }
    public String getThiroeidismos() {
        return this.thiroeidismos;
    }
    
    public void setThiroeidismos(String thiroeidismos) {
        this.thiroeidismos = thiroeidismos;
    }
    public String getMorfiThiroeidi() {
        return this.morfiThiroeidi;
    }
    
    public void setMorfiThiroeidi(String morfiThiroeidi) {
        this.morfiThiroeidi = morfiThiroeidi;
    }
    public String getAllesChroniesAstheneies() {
        return this.allesChroniesAstheneies;
    }
    
    public void setAllesChroniesAstheneies(String allesChroniesAstheneies) {
        this.allesChroniesAstheneies = allesChroniesAstheneies;
    }




}


