package vidavo.pojos;
// Generated 18.3.2010 19:46: by Hibernate Tools 3.2.1.GA



/**
 * Contacts generated by hbm2java
 */
public class Contacts  implements java.io.Serializable {


     private int contactId;
     private Patients patients;
     private String relationship;
     private String firstName;
     private String lastName;
     private String homePhone;
     private String email;
     private int patientId;

    public Contacts() {
    }

    public Contacts(String relationship, String firstName, String lastName, String homePhone, String email) {
       this.contactId = contactId;
       this.patients = patients;
       this.relationship = relationship;
       this.firstName = firstName;
       this.lastName = lastName;
       this.homePhone = homePhone;
       this.email = email;
       this.patientId = patientId;
    }
   
    public int getContactId() {
        return this.contactId;
    }
    
    public void setContactId(int contactId) {
        this.contactId = contactId;
    }
    public Patients getPatients() {
        return this.patients;
    }
    
    public void setPatients(Patients patients) {
        this.patients = patients;
    }
    public String getRelationship() {
        return this.relationship;
    }
    
    public void setRelationship(String relationship) {
        this.relationship = relationship;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public String getHomePhone() {
        return this.homePhone;
    }
    
    public void setHomePhone(String homePhone) {
        this.homePhone = homePhone;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public int getPatientId() {
        return this.patientId;
    }
    
    public void setPatientId(int patientId) {
        this.patientId = patientId;
    }




}


