package vidavo.pojos;
// Generated 18.3.2010 19:46: by Hibernate Tools 3.2.1.GA



/**
 * FamilyHistory generated by hbm2java
 */
public class FamilyHistory  implements java.io.Serializable {


     private int fhId;
     private Patients patients;
     private String egefalikoEpeisodio;
     private String diamartiesDiaplasisPneumonon;
     private String diamartiesDiaplasisKikloforikouSistimatos;
     private String diamartiesDiaplasisKardiakwnDiafragmatwn;
     private String kardiakiKoilotita;
     private String istorikoAsthmatos;
     private String diamartiesKardias;
     private String diamartiesTraxeiasVrohou;
     private String diaplasiDermatos;
     private String stenosiLeptouEnderou;
     private String stenosiPaxeosEnderou;
     private String diamartiesEnderou;
     private String diaplasiPeptikouSistimatos;
     private String nefrikiAgenesia;
     private String kistikiNososNefrwn;
     private String anomaliesNefrikisPyelou;
     private String diaplasiNeftwn;
     private String diataraxesNefrouOuritira;
     private String diaplasiOuritira;
     private String diaplasiOuropoiitikouSistimatos;
     private String klironomikiAnaimia;
     private String sigenisThiroeidismos;
     private String eleipsiLaktasis;
     private String disanexiaLaktozis;
     private String psixikesDiataraxes;
     private String istorikoSarkomatwn;
     private String kakoithiNeoplasmata;
     private String kataxrisiAlkool;
     private String klironomikosDiavitis;
     private String istorikoLeuxemias;
     private String allesMorfesOikogeneiakouIstorikou;

    public FamilyHistory() {
    }

	
    public FamilyHistory(int fhId, Patients patients) {
        this.fhId = fhId;
        this.patients = patients;
    }
    public FamilyHistory(String egefalikoEpeisodio, String diamartiesDiaplasisPneumonon, String diamartiesDiaplasisKikloforikouSistimatos, String diamartiesDiaplasisKardiakwnDiafragmatwn, String kardiakiKoilotita, String istorikoAsthmatos, String diamartiesKardias, String diamartiesTraxeiasVrohou, String diaplasiDermatos, String stenosiLeptouEnderou, String stenosiPaxeosEnderou, String diamartiesEnderou, String diaplasiPeptikouSistimatos, String nefrikiAgenesia, String kistikiNososNefrwn, String anomaliesNefrikisPyelou, String diaplasiNeftwn, String diataraxesNefrouOuritira, String diaplasiOuritira, String diaplasiOuropoiitikouSistimatos, String klironomikiAnaimia, String sigenisThiroeidismos, String eleipsiLaktasis, String disanexiaLaktozis, String psixikesDiataraxes, String istorikoSarkomatwn, String kakoithiNeoplasmata, String kataxrisiAlkool, String klironomikosDiavitis, String istorikoLeuxemias, String allesMorfesOikogeneiakouIstorikou) {
       this.fhId = fhId;
       this.patients = patients;
       this.egefalikoEpeisodio = egefalikoEpeisodio;
       this.diamartiesDiaplasisPneumonon = diamartiesDiaplasisPneumonon;
       this.diamartiesDiaplasisKikloforikouSistimatos = diamartiesDiaplasisKikloforikouSistimatos;
       this.diamartiesDiaplasisKardiakwnDiafragmatwn = diamartiesDiaplasisKardiakwnDiafragmatwn;
       this.kardiakiKoilotita = kardiakiKoilotita;
       this.istorikoAsthmatos = istorikoAsthmatos;
       this.diamartiesKardias = diamartiesKardias;
       this.diamartiesTraxeiasVrohou = diamartiesTraxeiasVrohou;
       this.diaplasiDermatos = diaplasiDermatos;
       this.stenosiLeptouEnderou = stenosiLeptouEnderou;
       this.stenosiPaxeosEnderou = stenosiPaxeosEnderou;
       this.diamartiesEnderou = diamartiesEnderou;
       this.diaplasiPeptikouSistimatos = diaplasiPeptikouSistimatos;
       this.nefrikiAgenesia = nefrikiAgenesia;
       this.kistikiNososNefrwn = kistikiNososNefrwn;
       this.anomaliesNefrikisPyelou = anomaliesNefrikisPyelou;
       this.diaplasiNeftwn = diaplasiNeftwn;
       this.diataraxesNefrouOuritira = diataraxesNefrouOuritira;
       this.diaplasiOuritira = diaplasiOuritira;
       this.diaplasiOuropoiitikouSistimatos = diaplasiOuropoiitikouSistimatos;
       this.klironomikiAnaimia = klironomikiAnaimia;
       this.sigenisThiroeidismos = sigenisThiroeidismos;
       this.eleipsiLaktasis = eleipsiLaktasis;
       this.disanexiaLaktozis = disanexiaLaktozis;
       this.psixikesDiataraxes = psixikesDiataraxes;
       this.istorikoSarkomatwn = istorikoSarkomatwn;
       this.kakoithiNeoplasmata = kakoithiNeoplasmata;
       this.kataxrisiAlkool = kataxrisiAlkool;
       this.klironomikosDiavitis = klironomikosDiavitis;
       this.istorikoLeuxemias = istorikoLeuxemias;
       this.allesMorfesOikogeneiakouIstorikou = allesMorfesOikogeneiakouIstorikou;
    }
   
    public int getFhId() {
        return this.fhId;
    }
    
    public void setFhId(int fhId) {
        this.fhId = fhId;
    }
    public Patients getPatients() {
        return this.patients;
    }
    
    public void setPatients(Patients patients) {
        this.patients = patients;
    }
    public String getEgefalikoEpeisodio() {
        return this.egefalikoEpeisodio;
    }
    
    public void setEgefalikoEpeisodio(String egefalikoEpeisodio) {
        this.egefalikoEpeisodio = egefalikoEpeisodio;
    }
    public String getDiamartiesDiaplasisPneumonon() {
        return this.diamartiesDiaplasisPneumonon;
    }
    
    public void setDiamartiesDiaplasisPneumonon(String diamartiesDiaplasisPneumonon) {
        this.diamartiesDiaplasisPneumonon = diamartiesDiaplasisPneumonon;
    }
    public String getDiamartiesDiaplasisKikloforikouSistimatos() {
        return this.diamartiesDiaplasisKikloforikouSistimatos;
    }
    
    public void setDiamartiesDiaplasisKikloforikouSistimatos(String diamartiesDiaplasisKikloforikouSistimatos) {
        this.diamartiesDiaplasisKikloforikouSistimatos = diamartiesDiaplasisKikloforikouSistimatos;
    }
    public String getDiamartiesDiaplasisKardiakwnDiafragmatwn() {
        return this.diamartiesDiaplasisKardiakwnDiafragmatwn;
    }
    
    public void setDiamartiesDiaplasisKardiakwnDiafragmatwn(String diamartiesDiaplasisKardiakwnDiafragmatwn) {
        this.diamartiesDiaplasisKardiakwnDiafragmatwn = diamartiesDiaplasisKardiakwnDiafragmatwn;
    }
    public String getKardiakiKoilotita() {
        return this.kardiakiKoilotita;
    }
    
    public void setKardiakiKoilotita(String kardiakiKoilotita) {
        this.kardiakiKoilotita = kardiakiKoilotita;
    }
    public String getIstorikoAsthmatos() {
        return this.istorikoAsthmatos;
    }
    
    public void setIstorikoAsthmatos(String istorikoAsthmatos) {
        this.istorikoAsthmatos = istorikoAsthmatos;
    }
    public String getDiamartiesKardias() {
        return this.diamartiesKardias;
    }
    
    public void setDiamartiesKardias(String diamartiesKardias) {
        this.diamartiesKardias = diamartiesKardias;
    }
    public String getDiamartiesTraxeiasVrohou() {
        return this.diamartiesTraxeiasVrohou;
    }
    
    public void setDiamartiesTraxeiasVrohou(String diamartiesTraxeiasVrohou) {
        this.diamartiesTraxeiasVrohou = diamartiesTraxeiasVrohou;
    }
    public String getDiaplasiDermatos() {
        return this.diaplasiDermatos;
    }
    
    public void setDiaplasiDermatos(String diaplasiDermatos) {
        this.diaplasiDermatos = diaplasiDermatos;
    }
    public String getStenosiLeptouEnderou() {
        return this.stenosiLeptouEnderou;
    }
    
    public void setStenosiLeptouEnderou(String stenosiLeptouEnderou) {
        this.stenosiLeptouEnderou = stenosiLeptouEnderou;
    }
    public String getStenosiPaxeosEnderou() {
        return this.stenosiPaxeosEnderou;
    }
    
    public void setStenosiPaxeosEnderou(String stenosiPaxeosEnderou) {
        this.stenosiPaxeosEnderou = stenosiPaxeosEnderou;
    }
    public String getDiamartiesEnderou() {
        return this.diamartiesEnderou;
    }
    
    public void setDiamartiesEnderou(String diamartiesEnderou) {
        this.diamartiesEnderou = diamartiesEnderou;
    }
    public String getDiaplasiPeptikouSistimatos() {
        return this.diaplasiPeptikouSistimatos;
    }
    
    public void setDiaplasiPeptikouSistimatos(String diaplasiPeptikouSistimatos) {
        this.diaplasiPeptikouSistimatos = diaplasiPeptikouSistimatos;
    }
    public String getNefrikiAgenesia() {
        return this.nefrikiAgenesia;
    }
    
    public void setNefrikiAgenesia(String nefrikiAgenesia) {
        this.nefrikiAgenesia = nefrikiAgenesia;
    }
    public String getKistikiNososNefrwn() {
        return this.kistikiNososNefrwn;
    }
    
    public void setKistikiNososNefrwn(String kistikiNososNefrwn) {
        this.kistikiNososNefrwn = kistikiNososNefrwn;
    }
    public String getAnomaliesNefrikisPyelou() {
        return this.anomaliesNefrikisPyelou;
    }
    
    public void setAnomaliesNefrikisPyelou(String anomaliesNefrikisPyelou) {
        this.anomaliesNefrikisPyelou = anomaliesNefrikisPyelou;
    }
    public String getDiaplasiNeftwn() {
        return this.diaplasiNeftwn;
    }
    
    public void setDiaplasiNeftwn(String diaplasiNeftwn) {
        this.diaplasiNeftwn = diaplasiNeftwn;
    }
    public String getDiataraxesNefrouOuritira() {
        return this.diataraxesNefrouOuritira;
    }
    
    public void setDiataraxesNefrouOuritira(String diataraxesNefrouOuritira) {
        this.diataraxesNefrouOuritira = diataraxesNefrouOuritira;
    }
    public String getDiaplasiOuritira() {
        return this.diaplasiOuritira;
    }
    
    public void setDiaplasiOuritira(String diaplasiOuritira) {
        this.diaplasiOuritira = diaplasiOuritira;
    }
    public String getDiaplasiOuropoiitikouSistimatos() {
        return this.diaplasiOuropoiitikouSistimatos;
    }
    
    public void setDiaplasiOuropoiitikouSistimatos(String diaplasiOuropoiitikouSistimatos) {
        this.diaplasiOuropoiitikouSistimatos = diaplasiOuropoiitikouSistimatos;
    }
    public String getKlironomikiAnaimia() {
        return this.klironomikiAnaimia;
    }
    
    public void setKlironomikiAnaimia(String klironomikiAnaimia) {
        this.klironomikiAnaimia = klironomikiAnaimia;
    }
    public String getSigenisThiroeidismos() {
        return this.sigenisThiroeidismos;
    }
    
    public void setSigenisThiroeidismos(String sigenisThiroeidismos) {
        this.sigenisThiroeidismos = sigenisThiroeidismos;
    }
    public String getEleipsiLaktasis() {
        return this.eleipsiLaktasis;
    }
    
    public void setEleipsiLaktasis(String eleipsiLaktasis) {
        this.eleipsiLaktasis = eleipsiLaktasis;
    }
    public String getDisanexiaLaktozis() {
        return this.disanexiaLaktozis;
    }
    
    public void setDisanexiaLaktozis(String disanexiaLaktozis) {
        this.disanexiaLaktozis = disanexiaLaktozis;
    }
    public String getPsixikesDiataraxes() {
        return this.psixikesDiataraxes;
    }
    
    public void setPsixikesDiataraxes(String psixikesDiataraxes) {
        this.psixikesDiataraxes = psixikesDiataraxes;
    }
    public String getIstorikoSarkomatwn() {
        return this.istorikoSarkomatwn;
    }
    
    public void setIstorikoSarkomatwn(String istorikoSarkomatwn) {
        this.istorikoSarkomatwn = istorikoSarkomatwn;
    }
    public String getKakoithiNeoplasmata() {
        return this.kakoithiNeoplasmata;
    }
    
    public void setKakoithiNeoplasmata(String kakoithiNeoplasmata) {
        this.kakoithiNeoplasmata = kakoithiNeoplasmata;
    }
    public String getKataxrisiAlkool() {
        return this.kataxrisiAlkool;
    }
    
    public void setKataxrisiAlkool(String kataxrisiAlkool) {
        this.kataxrisiAlkool = kataxrisiAlkool;
    }
    public String getKlironomikosDiavitis() {
        return this.klironomikosDiavitis;
    }
    
    public void setKlironomikosDiavitis(String klironomikosDiavitis) {
        this.klironomikosDiavitis = klironomikosDiavitis;
    }
    public String getIstorikoLeuxemias() {
        return this.istorikoLeuxemias;
    }
    
    public void setIstorikoLeuxemias(String istorikoLeuxemias) {
        this.istorikoLeuxemias = istorikoLeuxemias;
    }
    public String getAllesMorfesOikogeneiakouIstorikou() {
        return this.allesMorfesOikogeneiakouIstorikou;
    }
    
    public void setAllesMorfesOikogeneiakouIstorikou(String allesMorfesOikogeneiakouIstorikou) {
        this.allesMorfesOikogeneiakouIstorikou = allesMorfesOikogeneiakouIstorikou;
    }




}


