package vidavo.pojos;
// Generated 9.3.2010 22:42: by Hibernate Tools 3.2.1.GA



/**
 * Habits generated by hbm2java
 */
public class Habits  implements java.io.Serializable {


     private int habitsId;
     private Patients patients;
     private String smoker;
     private String howLongSmoke;
     private String tea;
     private String coffee;
     private String softdrinks;
     private String caffeinePerDay;
     private String saltUsage;
     private String sugarUsage;
     private String diet;
     private String foodHabits;
     private String alcoholPerDay;
     private String alcoholPerWeek;
     private String useOfDrugs;
     private String useOfMedication;
     private String exercise;
     private String exerciseType;
     private String exerciseHowOften;
     private String otherHabits;

    public Habits() {
    }

	
    public Habits(int habitsId, Patients patients) {
        this.habitsId = habitsId;
        this.patients = patients;
    }
    public Habits(String smoker, String howLongSmoke, String tea, String coffee, String softdrinks, String caffeinePerDay, String saltUsage, String sugarUsage, String diet, String foodHabits, String alcoholPerDay, String alcoholPerWeek, String useOfDrugs, String useOfMedication, String exercise, String exerciseType, String exerciseHowOften, String otherHabits) {
       this.habitsId = habitsId;
       this.patients = patients;
       this.smoker = smoker;
       this.howLongSmoke = howLongSmoke;
       this.tea = tea;
       this.coffee = coffee;
       this.softdrinks = softdrinks;
       this.caffeinePerDay = caffeinePerDay;
       this.saltUsage = saltUsage;
       this.sugarUsage = sugarUsage;
       this.diet = diet;
       this.foodHabits = foodHabits;
       this.alcoholPerDay = alcoholPerDay;
       this.alcoholPerWeek = alcoholPerWeek;
       this.useOfDrugs = useOfDrugs;
       this.useOfMedication = useOfMedication;
       this.exercise = exercise;
       this.exerciseType = exerciseType;
       this.exerciseHowOften = exerciseHowOften;
       this.otherHabits = otherHabits;
    }
   
    public int getHabitsId() {
        return this.habitsId;
    }
    
    public void setHabitsId(int habitsId) {
        this.habitsId = habitsId;
    }
    public Patients getPatients() {
        return this.patients;
    }
    
    public void setPatients(Patients patients) {
        this.patients = patients;
    }
    public String getSmoker() {
        return this.smoker;
    }
    
    public void setSmoker(String smoker) {
        this.smoker = smoker;
    }
    public String getHowLongSmoke() {
        return this.howLongSmoke;
    }
    
    public void setHowLongSmoke(String howLongSmoke) {
        this.howLongSmoke = howLongSmoke;
    }
    public String getTea() {
        return this.tea;
    }
    
    public void setTea(String tea) {
        this.tea = tea;
    }
    public String getCoffee() {
        return this.coffee;
    }
    
    public void setCoffee(String coffee) {
        this.coffee = coffee;
    }
    public String getSoftdrinks() {
        return this.softdrinks;
    }
    
    public void setSoftdrinks(String softdrinks) {
        this.softdrinks = softdrinks;
    }
    public String getCaffeinePerDay() {
        return this.caffeinePerDay;
    }
    
    public void setCaffeinePerDay(String caffeinePerDay) {
        this.caffeinePerDay = caffeinePerDay;
    }
    public String getSaltUsage() {
        return this.saltUsage;
    }
    
    public void setSaltUsage(String saltUsage) {
        this.saltUsage = saltUsage;
    }
    public String getSugarUsage() {
        return this.sugarUsage;
    }
    
    public void setSugarUsage(String sugarUsage) {
        this.sugarUsage = sugarUsage;
    }
    public String getDiet() {
        return this.diet;
    }
    
    public void setDiet(String diet) {
        this.diet = diet;
    }
    public String getFoodHabits() {
        return this.foodHabits;
    }
    
    public void setFoodHabits(String foodHabits) {
        this.foodHabits = foodHabits;
    }
    public String getAlcoholPerDay() {
        return this.alcoholPerDay;
    }
    
    public void setAlcoholPerDay(String alcoholPerDay) {
        this.alcoholPerDay = alcoholPerDay;
    }
    public String getAlcoholPerWeek() {
        return this.alcoholPerWeek;
    }
    
    public void setAlcoholPerWeek(String alcoholPerWeek) {
        this.alcoholPerWeek = alcoholPerWeek;
    }
    public String getUseOfDrugs() {
        return this.useOfDrugs;
    }
    
    public void setUseOfDrugs(String useOfDrugs) {
        this.useOfDrugs = useOfDrugs;
    }
    public String getUseOfMedication() {
        return this.useOfMedication;
    }
    
    public void setUseOfMedication(String useOfMedication) {
        this.useOfMedication = useOfMedication;
    }
    public String getExercise() {
        return this.exercise;
    }
    
    public void setExercise(String exercise) {
        this.exercise = exercise;
    }
    public String getExerciseType() {
        return this.exerciseType;
    }
    
    public void setExerciseType(String exerciseType) {
        this.exerciseType = exerciseType;
    }
    public String getExerciseHowOften() {
        return this.exerciseHowOften;
    }
    
    public void setExerciseHowOften(String exerciseHowOften) {
        this.exerciseHowOften = exerciseHowOften;
    }
    public String getOtherHabits() {
        return this.otherHabits;
    }
    
    public void setOtherHabits(String otherHabits) {
        this.otherHabits = otherHabits;
    }




}


