package vidavo.pojos;
// Generated 11.3.2010 18:33: by Hibernate Tools 3.2.1.GA



/**
 * Immunizations generated by hbm2java
 */
public class Immunizations  implements java.io.Serializable {


     private int immunId;
     private Patients patients;
     private String bloodType;
     private String bloodDonor;
     private String bloodBank;
     private String bloodContageousDiseases;
     private String bleedingProlems;
     private String doritisMielouOston;
     private String kidneyDonor;
     private String doritisAllonOrganon;
     private String allergies;
     private String allergiesToDrugs;
     private String poorCirculation;
     private String stigma;

    public Immunizations() {
    }

	
    public Immunizations(int immunId, Patients patients) {
        this.immunId = immunId;
        this.patients = patients;
    }
    public Immunizations(String bloodType, String bloodDonor, String bloodBank, String bloodContageousDiseases, String bleedingProlems, String doritisMielouOston, String kidneyDonor, String doritisAllonOrganon, String allergies, String allergiesToDrugs, String poorCirculation, String stigma) {
       this.immunId = immunId;
       this.patients = patients;
       this.bloodType = bloodType;
       this.bloodDonor = bloodDonor;
       this.bloodBank = bloodBank;
       this.bloodContageousDiseases = bloodContageousDiseases;
       this.bleedingProlems = bleedingProlems;
       this.doritisMielouOston = doritisMielouOston;
       this.kidneyDonor = kidneyDonor;
       this.doritisAllonOrganon = doritisAllonOrganon;
       this.allergies = allergies;
       this.allergiesToDrugs = allergiesToDrugs;
       this.poorCirculation = poorCirculation;
       this.stigma = stigma;
    }
   
    public int getImmunId() {
        return this.immunId;
    }
    
    public void setImmunId(int immunId) {
        this.immunId = immunId;
    }
    public Patients getPatients() {
        return this.patients;
    }
    
    public void setPatients(Patients patients) {
        this.patients = patients;
    }
    public String getBloodType() {
        return this.bloodType;
    }
    
    public void setBloodType(String bloodType) {
        this.bloodType = bloodType;
    }
    public String getBloodDonor() {
        return this.bloodDonor;
    }
    
    public void setBloodDonor(String bloodDonor) {
        this.bloodDonor = bloodDonor;
    }
    public String getBloodBank() {
        return this.bloodBank;
    }
    
    public void setBloodBank(String bloodBank) {
        this.bloodBank = bloodBank;
    }
    public String getBloodContageousDiseases() {
        return this.bloodContageousDiseases;
    }
    
    public void setBloodContageousDiseases(String bloodContageousDiseases) {
        this.bloodContageousDiseases = bloodContageousDiseases;
    }
    public String getBleedingProlems() {
        return this.bleedingProlems;
    }
    
    public void setBleedingProlems(String bleedingProlems) {
        this.bleedingProlems = bleedingProlems;
    }
    public String getDoritisMielouOston() {
        return this.doritisMielouOston;
    }
    
    public void setDoritisMielouOston(String doritisMielouOston) {
        this.doritisMielouOston = doritisMielouOston;
    }
    public String getKidneyDonor() {
        return this.kidneyDonor;
    }
    
    public void setKidneyDonor(String kidneyDonor) {
        this.kidneyDonor = kidneyDonor;
    }
    public String getDoritisAllonOrganon() {
        return this.doritisAllonOrganon;
    }
    
    public void setDoritisAllonOrganon(String doritisAllonOrganon) {
        this.doritisAllonOrganon = doritisAllonOrganon;
    }
    public String getAllergies() {
        return this.allergies;
    }
    
    public void setAllergies(String allergies) {
        this.allergies = allergies;
    }
    public String getAllergiesToDrugs() {
        return this.allergiesToDrugs;
    }
    
    public void setAllergiesToDrugs(String allergiesToDrugs) {
        this.allergiesToDrugs = allergiesToDrugs;
    }
    public String getPoorCirculation() {
        return this.poorCirculation;
    }
    
    public void setPoorCirculation(String poorCirculation) {
        this.poorCirculation = poorCirculation;
    }
    public String getStigma() {
        return this.stigma;
    }
    
    public void setStigma(String stigma) {
        this.stigma = stigma;
    }




}


