package vidavo.pojos;
// Generated 11.3.2010 18:33: by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Patients generated by hbm2java
 */
public class Patients  implements java.io.Serializable {


     private int patientId;
     private Set personalInfos = new HashSet(0);
     private Set chronicMedications = new HashSet(0);
     private Set chronicDiseaseses = new HashSet(0);
     private Set familyHistories = new HashSet(0);
     private Set appointmentses = new HashSet(0);
     private Set contactses = new HashSet(0);
     private Set habitses = new HashSet(0);
     private Set immunizationses = new HashSet(0);
     private Set surgicalHistories = new HashSet(0);

    public Patients() {
    }

	
    public Patients(int patientId) {
        this.patientId = patientId;
    }
    public Patients(int patientId, Set personalInfos, Set chronicMedications, Set chronicDiseaseses, Set familyHistories, Set appointmentses, Set contactses, Set habitses, Set immunizationses, Set surgicalHistories) {
       this.patientId = patientId;
       this.personalInfos = personalInfos;
       this.chronicMedications = chronicMedications;
       this.chronicDiseaseses = chronicDiseaseses;
       this.familyHistories = familyHistories;
       this.appointmentses = appointmentses;
       this.contactses = contactses;
       this.habitses = habitses;
       this.immunizationses = immunizationses;
       this.surgicalHistories = surgicalHistories;
    }
   
    public int getPatientId() {
        return this.patientId;
    }
    
    public void setPatientId(int patientId) {
        this.patientId = patientId;
    }
    public Set getPersonalInfos() {
        return this.personalInfos;
    }
    
    public void setPersonalInfos(Set personalInfos) {
        this.personalInfos = personalInfos;
    }
    public Set getChronicMedications() {
        return this.chronicMedications;
    }
    
    public void setChronicMedications(Set chronicMedications) {
        this.chronicMedications = chronicMedications;
    }
    public Set getChronicDiseaseses() {
        return this.chronicDiseaseses;
    }
    
    public void setChronicDiseaseses(Set chronicDiseaseses) {
        this.chronicDiseaseses = chronicDiseaseses;
    }
    public Set getFamilyHistories() {
        return this.familyHistories;
    }
    
    public void setFamilyHistories(Set familyHistories) {
        this.familyHistories = familyHistories;
    }
    public Set getAppointmentses() {
        return this.appointmentses;
    }
    
    public void setAppointmentses(Set appointmentses) {
        this.appointmentses = appointmentses;
    }
    public Set getContactses() {
        return this.contactses;
    }
    
    public void setContactses(Set contactses) {
        this.contactses = contactses;
    }
    public Set getHabitses() {
        return this.habitses;
    }
    
    public void setHabitses(Set habitses) {
        this.habitses = habitses;
    }
    public Set getImmunizationses() {
        return this.immunizationses;
    }
    
    public void setImmunizationses(Set immunizationses) {
        this.immunizationses = immunizationses;
    }
    public Set getSurgicalHistories() {
        return this.surgicalHistories;
    }
    
    public void setSurgicalHistories(Set surgicalHistories) {
        this.surgicalHistories = surgicalHistories;
    }




}


