package vidavo.pojos;
// Generated 9.3.2010 22:42: by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * PersonalInfo generated by hbm2java
 */
public class PersonalInfo  implements java.io.Serializable {


     private int piId;
     private Patients patients;
     private String firstName;
     private String middleName;
     private String lastName;
     private String address;
     private Integer addressNum;
     private String city;
     private String stateRegion;
     private String country;
     private Integer postalCode;
     private String citizenship;
     private Integer height;
     private Float weight;
     private String gender;
     private String status;
     private Date birthDate;
     private String profession;
     private String insurrance;
     private String insuranceType;
     private int insuranceIdNumber;
     private Date firstVisit;
     private Integer children;
     private Integer homeNumber;
     private Integer cellPhoneNumber;
     private Integer workNumber;
     private Integer faxNumber;
     private String email;

    public PersonalInfo() {
    }

	
    public PersonalInfo(int piId, Patients patients, String firstName, String lastName, String insurrance, String insuranceType, int insuranceIdNumber) {
        this.piId = piId;
        this.patients = patients;
        this.firstName = firstName;
        this.lastName = lastName;
        this.insurrance = insurrance;
        this.insuranceType = insuranceType;
        this.insuranceIdNumber = insuranceIdNumber;
    }
    public PersonalInfo(String firstName, String middleName, String lastName, String address, Integer addressNum, String city, String stateRegion, String country, Integer postalCode, String citizenship, Integer height, Float weight, String gender, String status, Date birthDate, String profession, String insurrance, String insuranceType, int insuranceIdNumber, Date firstVisit, Integer children, Integer homeNumber, Integer cellPhoneNumber, Integer workNumber, Integer faxNumber, String email) {
       this.piId = piId;
       this.patients = patients;
       this.firstName = firstName;
       this.middleName = middleName;
       this.lastName = lastName;
       this.address = address;
       this.addressNum = addressNum;
       this.city = city;
       this.stateRegion = stateRegion;
       this.country = country;
       this.postalCode = postalCode;
       this.citizenship = citizenship;
       this.height = height;
       this.weight = weight;
       this.gender = gender;
       this.status = status;
       this.birthDate = birthDate;
       this.profession = profession;
       this.insurrance = insurrance;
       this.insuranceType = insuranceType;
       this.insuranceIdNumber = insuranceIdNumber;
       this.firstVisit = firstVisit;
       this.children = children;
       this.homeNumber = homeNumber;
       this.cellPhoneNumber = cellPhoneNumber;
       this.workNumber = workNumber;
       this.faxNumber = faxNumber;
       this.email = email;
    }
   
    public int getPiId() {
        return this.piId;
    }
    
    public void setPiId(int piId) {
        this.piId = piId;
    }
    public Patients getPatients() {
        return this.patients;
    }
    
    public void setPatients(Patients patients) {
        this.patients = patients;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getMiddleName() {
        return this.middleName;
    }
    
    public void setMiddleName(String middleName) {
        this.middleName = middleName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public Integer getAddressNum() {
        return this.addressNum;
    }
    
    public void setAddressNum(Integer addressNum) {
        this.addressNum = addressNum;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public String getStateRegion() {
        return this.stateRegion;
    }
    
    public void setStateRegion(String stateRegion) {
        this.stateRegion = stateRegion;
    }
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }
    public Integer getPostalCode() {
        return this.postalCode;
    }
    
    public void setPostalCode(Integer postalCode) {
        this.postalCode = postalCode;
    }
    public String getCitizenship() {
        return this.citizenship;
    }
    
    public void setCitizenship(String citizenship) {
        this.citizenship = citizenship;
    }
    public Integer getHeight() {
        return this.height;
    }
    
    public void setHeight(Integer height) {
        this.height = height;
    }
    public Float getWeight() {
        return this.weight;
    }
    
    public void setWeight(Float weight) {
        this.weight = weight;
    }
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Date getBirthDate() {
        return this.birthDate;
    }
    
    public void setBirthDate(Date birthDate) {
        this.birthDate = birthDate;
    }
    public String getProfession() {
        return this.profession;
    }
    
    public void setProfession(String profession) {
        this.profession = profession;
    }
    public String getInsurrance() {
        return this.insurrance;
    }
    
    public void setInsurrance(String insurrance) {
        this.insurrance = insurrance;
    }
    public String getInsuranceType() {
        return this.insuranceType;
    }
    
    public void setInsuranceType(String insuranceType) {
        this.insuranceType = insuranceType;
    }
    public int getInsuranceIdNumber() {
        return this.insuranceIdNumber;
    }
    
    public void setInsuranceIdNumber(int insuranceIdNumber) {
        this.insuranceIdNumber = insuranceIdNumber;
    }
    public Date getFirstVisit() {
        return this.firstVisit;
    }
    
    public void setFirstVisit(Date firstVisit) {
        this.firstVisit = firstVisit;
    }
    public Integer getChildren() {
        return this.children;
    }
    
    public void setChildren(Integer children) {
        this.children = children;
    }
    public Integer getHomeNumber() {
        return this.homeNumber;
    }
    
    public void setHomeNumber(Integer homeNumber) {
        this.homeNumber = homeNumber;
    }
    public Integer getCellPhoneNumber() {
        return this.cellPhoneNumber;
    }
    
    public void setCellPhoneNumber(Integer cellPhoneNumber) {
        this.cellPhoneNumber = cellPhoneNumber;
    }
    public Integer getWorkNumber() {
        return this.workNumber;
    }
    
    public void setWorkNumber(Integer workNumber) {
        this.workNumber = workNumber;
    }
    public Integer getFaxNumber() {
        return this.faxNumber;
    }
    
    public void setFaxNumber(Integer faxNumber) {
        this.faxNumber = faxNumber;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }




}


