package vidavo.pojos;
// Generated 9.3.2010 22:42: by Hibernate Tools 3.2.1.GA



/**
 * SurgicalHistory generated by hbm2java
 */
public class SurgicalHistory  implements java.io.Serializable {


     private int shId;
     private Patients patients;
     private String descriptionOfSurgery;
     private String hospitalName;
     private String reasonOfHospitalization;
     private String finalDiagnosis;
     private String doctorsName;

    public SurgicalHistory() {
    }

	
    public SurgicalHistory(int shId, Patients patients) {
        this.shId = shId;
        this.patients = patients;
    }
    public SurgicalHistory(String descriptionOfSurgery, String hospitalName, String reasonOfHospitalization, String finalDiagnosis, String doctorsName) {
       this.shId = shId;
       this.patients = patients;
       this.descriptionOfSurgery = descriptionOfSurgery;
       this.hospitalName = hospitalName;
       this.reasonOfHospitalization = reasonOfHospitalization;
       this.finalDiagnosis = finalDiagnosis;
       this.doctorsName = doctorsName;
    }
   
    public int getShId() {
        return this.shId;
    }
    
    public void setShId(int shId) {
        this.shId = shId;
    }
    public Patients getPatients() {
        return this.patients;
    }
    
    public void setPatients(Patients patients) {
        this.patients = patients;
    }
    public String getDescriptionOfSurgery() {
        return this.descriptionOfSurgery;
    }
    
    public void setDescriptionOfSurgery(String descriptionOfSurgery) {
        this.descriptionOfSurgery = descriptionOfSurgery;
    }
    public String getHospitalName() {
        return this.hospitalName;
    }
    
    public void setHospitalName(String hospitalName) {
        this.hospitalName = hospitalName;
    }
    public String getReasonOfHospitalization() {
        return this.reasonOfHospitalization;
    }
    
    public void setReasonOfHospitalization(String reasonOfHospitalization) {
        this.reasonOfHospitalization = reasonOfHospitalization;
    }
    public String getFinalDiagnosis() {
        return this.finalDiagnosis;
    }
    
    public void setFinalDiagnosis(String finalDiagnosis) {
        this.finalDiagnosis = finalDiagnosis;
    }
    public String getDoctorsName() {
        return this.doctorsName;
    }
    
    public void setDoctorsName(String doctorsName) {
        this.doctorsName = doctorsName;
    }




}


